[package]
name = "overseer_util"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nonzero_ext = "0.2.0"
serde = "1.0.126"
serde-diff = { git = "https://github.com/AaronFriel/serde-diff", features = ["im"], rev = "cebff2dbba7a4f8d1d450d3a55062c17b2b8d1cd" }
