[workspace]

members = [
  "rs/magistrate",
  "rs/substrate_macros",
  "rs/substrate_core",
  "rs/substrate",
  # "rs/cli",
  # "rs/sandbox",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
# opt-level = "s"
lto = true
